# Konfigurasi paramter untuk ML pipeline

data:
  raw_path: "data/raw/churn_data.csv"
  processed_path: "data/processed/churn_processed.csv"
  test_size: 0.2
  random_state: 42
  val_size: 0.1

preprocess:
  numerical_features:
    - tenure
    - MonthlyCharges
    - TotalCharges
  
  categorical_features:
    - gender
    - Contract
    - PaymentMethod
    - InternetService
    - tenure_group
  
  target: Churn

  handle_missing: median
  scale_method: standard

  feature_engineering:
    create_tenure_bins: true 
    create_charge_ratio: true

train:
  model_type: random_forest

  # Hyperparameter
  n_estimators: 100
  max_depth: 10
  min_samples_split: 5
  min_samples_leaf: 2
  max_features: sqrt
  random_state: 42
  n_jobs: -1

  # Konfigurasi Training
  class_weight: balanced
  verbose: 1

evaluate:
  metrics_path: metrics/metrics.json
  model_path: models/churn_model.pkl


  # Evaluation Thresholds
  min_accuracy: 0.75
  min_f1_score: 0.70

  # Output_options
  save_confusion_matrix: true
  save_feature_importance: true

predict:
  batch_size: 1000
  output_probabilities: true
  